# Generated by Django 2.1.5 on 2020-06-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_rating', models.DecimalField(decimal_places=2, max_digits=10)),
                ('movie_genre', models.CharField(max_length=20)),
            ],
        ),
    ]
